# terraform/variables.tf
#
# All variables are populated by generated .auto.tfvars.json files or
# terraform.tfvars (not committed — see terraform.tfvars.example).
#
# Generated variables (do not edit manually — run generate_tf.py):
#   databases, warehouses, connector_roles, object_roles,
#   connector_to_object_role_grants, connector_to_warehouse_grants,
#   connector_type_mapping

# ---------------------------------------------------------------------------
# Shared configuration
# ---------------------------------------------------------------------------

variable "environment" {
  description = "Environment tag value (prod, staging, dev)"
  type        = string
  default     = "prod"
}

variable "resource_monitor_notify_users" {
  description = "Snowflake usernames to notify on resource monitor threshold events"
  type        = list(string)
  default     = []
}

# ---------------------------------------------------------------------------
# Generated by generate_tf.py — do not edit manually
# ---------------------------------------------------------------------------

variable "databases" {
  description = "Databases to create — generated from connectors.yaml by generate_tf.py"
  type = map(object({
    schemas = list(string)
    comment = string
  }))
  default = {}
}

variable "warehouses" {
  description = "Warehouses to create — generated from connectors.yaml by generate_tf.py"
  type = map(object({
    size                  = string
    auto_suspend_seconds  = number
    auto_resume           = bool
    monthly_credit_quota  = number
    notify_at_percentage  = number
    suspend_at_percentage = number
    comment               = string
  }))
  default = {}
}

variable "connector_roles" {
  description = "Connector roles — generated from connectors.yaml by generate_tf.py"
  type = map(object({
    name      = string
    reason    = string
    type      = string
    warehouse = string
  }))
  default = {}
}

variable "object_roles" {
  description = "Object roles — generated from connectors.yaml by generate_tf.py"
  type = map(object({
    database     = string
    tier         = string
    privileges   = list(string)
    extra_grants = list(string)
    schemas      = list(string)
    comment      = string
  }))
  default = {}
}

variable "connector_to_object_role_grants" {
  description = "Connector → object role grant mappings — generated by generate_tf.py"
  type = list(object({
    connector_role = string
    object_role    = string
  }))
  default = []
}

variable "connector_to_warehouse_grants" {
  description = "Connector → warehouse grant mappings — generated by generate_tf.py"
  type = list(object({
    connector_role = string
    warehouse      = string
  }))
  default = []
}

variable "connector_type_mapping" {
  description = "Connector role → functional type mapping — generated by generate_tf.py"
  type        = map(string)
  default     = {}
}

variable "functional_roles" {
  description = "Human functional roles — generated from team.yaml by generate_tf.py"
  type = list(object({
    name      = string
    warehouse = string
    reason    = string
  }))
  default = []
}

variable "functional_role_grants" {
  description = "Flattened privilege grants for human functional roles — generated from team.yaml by generate_tf.py"
  type = list(object({
    role      = string
    database  = string
    schema    = optional(string)
    privilege = string
    future    = bool
  }))
  default = []
}
