# terraform/modules/rbac/connectors.tf
#
# CONN_{NAME} connector roles — one per integration, generated from connectors.yaml.
#
# Each connector role:
#   - Gets a descriptive comment with the documented reason (PHILOSOPHY.md §5)
#   - Is granted USAGE on its assigned warehouse
#   - Is granted the appropriate object role(s)
#   - Transfers object ownership to SYSADMIN (see PHILOSOPHY.md §7)
#   - Is wired to the appropriate functional role by type
#
# Adding a new integration = add entry to connectors.yaml + terraform apply.
# No changes to this file are required.
#
# See PHILOSOPHY.md §The Connector Role Philosophy:
#   "The connector layer is defined in connectors.yaml and generated by Terraform.
#    Adding a new integration is a YAML entry, not a Terraform module change."

# ---------------------------------------------------------------------------
# Connector roles
# ---------------------------------------------------------------------------

resource "snowflake_account_role" "connector" {
  for_each = var.connector_roles

  name    = each.key
  comment = each.value.reason
}

# ---------------------------------------------------------------------------
# Object ownership transfer to SYSADMIN
#
# All objects created by connector roles have ownership transferred to SYSADMIN.
# The COPY CURRENT GRANTS clause preserves existing grants on the object.
#
# See PHILOSOPHY.md §Core Principles #7:
#   "All objects created by connector roles have ownership transferred to SYSADMIN
#    immediately after creation, using GRANT OWNERSHIP ... COPY CURRENT GRANTS."
# ---------------------------------------------------------------------------

resource "snowflake_grant_ownership" "connector_ownership" {
  for_each = var.connector_roles

  account_role_name   = "SYSADMIN"
  outbound_privileges = "COPY"

  on {
    object_type = "ROLE"
    object_name = snowflake_account_role.connector[each.key].name
  }

  depends_on = [snowflake_account_role.connector]
}

# ---------------------------------------------------------------------------
# Connector → object role grants
# ---------------------------------------------------------------------------

resource "snowflake_grant_account_role" "connector_to_object" {
  for_each = {
    for item in var.connector_to_object_role_grants :
    "${item.connector_role}->${item.object_role}" => item
  }

  role_name        = each.value.object_role
  parent_role_name = snowflake_account_role.connector[each.value.connector_role].name
}

# ---------------------------------------------------------------------------
# Connector → warehouse USAGE grants
# ---------------------------------------------------------------------------

resource "snowflake_grant_privileges_to_account_role" "connector_warehouse_usage" {
  for_each = {
    for item in var.connector_to_warehouse_grants :
    "${item.connector_role}->WH" => item
  }

  account_role_name = snowflake_account_role.connector[each.value.connector_role].name
  privileges        = ["USAGE"]

  on_account_object {
    object_type = "WAREHOUSE"
    object_name = each.value.warehouse
  }
}

# ---------------------------------------------------------------------------
# Connector → functional role hierarchy
#
# Connector roles are wired to the appropriate functional role by type.
# This is for auditing and documentation only — functional roles are
# conceptual, not operational.
# ---------------------------------------------------------------------------

locals {
  # Map connector type → functional role name
  type_to_functional = {
    etl          = "LOADER"
    orchestrator = "LOADER"
    event_stream = "LOADER"
    transformer  = "TRANSFORMER"
    bi_tool      = "ANALYST"
    custom       = "LOADER" # default — override in decisions.md if needed
  }
}

resource "snowflake_grant_account_role" "connector_to_functional" {
  for_each = var.connector_roles

  role_name        = snowflake_account_role.connector[each.key].name
  parent_role_name = local.type_to_functional[each.value.type]

  depends_on = [
    snowflake_account_role.connector,
  ]
}
